### ISSUE TITLE
SJR::setValue always do extra copy of std::string

### ISSUE THREAD

**Issue by oficsu** [Solisuom/SJR#3]
The first is when method accepts `newValue` by value and the second when calls assignment operator of `std::string`.

This can be fixed by different ways:
* the first option is to use `std::move` with assignment operator;
* the second is to pass the newValue by const reference, there will be one copy;
* the third is to use perfect forwarding, more info is [here](http://thbecker.net/articles/rvalue_references/section_01.html)

**Comment by LuridHound** [comment]
Done.
Commit : https://github.com/Solisuom/SJR/commit/b1316f802860801bf7940ca248d35a9042d59fd7
